"""Initial migration with Substance and Mixture models

Revision ID: 18c1bb3983dc
Revises: 
Create Date: 2025-11-30 13:17:55.947433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c1bb3983dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('final_health_hazards', sa.Text(), nullable=True),
    sa.Column('final_environmental_hazards', sa.Text(), nullable=True),
    sa.Column('final_ghs_codes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('substance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cas_number', sa.String(length=20), nullable=True),
    sa.Column('ghs_codes', sa.String(length=100), nullable=True),
    sa.Column('health_h_phrases', sa.Text(), nullable=True),
    sa.Column('env_h_phrases', sa.Text(), nullable=True),
    sa.Column('ate_oral', sa.Float(), nullable=True),
    sa.Column('ate_dermal', sa.Float(), nullable=True),
    sa.Column('ate_inhalation_vapours', sa.Float(), nullable=True),
    sa.Column('ate_inhalation_dusts_mists', sa.Float(), nullable=True),
    sa.Column('ate_inhalation_gases', sa.Float(), nullable=True),
    sa.Column('m_factor_acute', sa.Integer(), nullable=True),
    sa.Column('m_factor_chronic', sa.Integer(), nullable=True),
    sa.Column('scls', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mixture_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mixture_id', sa.Integer(), nullable=False),
    sa.Column('substance_id', sa.Integer(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mixture_id'], ['mixture.id'], ),
    sa.ForeignKeyConstraint(['substance_id'], ['substance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mixture_id', 'substance_id', name='_mixture_substance_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mixture_component')
    op.drop_table('substance')
    op.drop_table('mixture')
    # ### end Alembic commands ###
