"""Removed default=1 for M-factors

Revision ID: 80fbf39c7926
Revises: 18c1bb3983dc
Create Date: 2025-11-30 16:34:39.080934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fbf39c7926'
down_revision = '18c1bb3983dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scl_limits', sa.Text(), nullable=True))
        batch_op.drop_column('scls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scls', sa.TEXT(), nullable=True))
        batch_op.drop_column('scl_limits')

    # ### end Alembic commands ###
