"""Added ATEmix and Signal Word to Mixture model

Revision ID: ac9ac49ced3e
Revises: 80fbf39c7926
Create Date: 2025-11-30 17:07:24.668096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9ac49ced3e'
down_revision = '80fbf39c7926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_atemix_oral', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_atemix_dermal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_atemix_inhalation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_signal_word', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_column('final_signal_word')
        batch_op.drop_column('final_atemix_inhalation')
        batch_op.drop_column('final_atemix_dermal')
        batch_op.drop_column('final_atemix_oral')

    # ### end Alembic commands ###
