# app/constants/clp.py
# --- Převodní Tabulky ATE (Dle Přílohy I, Tabulka 3.1.2 CLP) ---
ATE_LIMITS = {
    "oral": [5, 50, 300, 2000],
    "dermal": [50, 200, 1000, 2000],
    "gas": [100, 500, 2500, 20000],
    "vapour": [0.5, 2, 10, 20],
    "dust_mist": [0.05, 0.5, 1, 5],
}

ATE_POINT_ESTIMATES = {
    "oral": {1: 0.5, 2: 5.0, 3: 100.0, 4: 500.0},
    "dermal": {1: 5.0, 2: 50.0, 3: 300.0, 4: 1100.0},
    "gas": {1: 10.0, 2: 100.0, 3: 700.0, 4: 4500.0},
    "vapour": {1: 0.05, 2: 0.5, 3: 3.0, 4: 11.0},
    "dust_mist": {1: 0.005, 2: 0.05, 3: 0.5, 4: 1.5},
}

ACUTE_TOXICITY_MAP = {
    1: {"h_code": "H300/H310/H330", "ghs": "GHS06", "signal_word": "NEBEZPEČÍ"},
    2: {"h_code": "H300/H310/H330", "ghs": "GHS06", "signal_word": "NEBEZPEČÍ"},
    3: {"h_code": "H301/H311/H331", "ghs": "GHS06", "signal_word": "NEBEZPEČÍ"},
    4: {"h_code": "H302/H312/H332", "ghs": "GHS07", "signal_word": "VAROVÁNÍ"},
    5: {"h_code": None, "ghs": None, "signal_word": None},
}

STANDARD_CONCENTRATION_LIMITS = {
    "Skin Corr. 1": {"h_code": "H314", "cl": 5.0, "ghs": "GHS05"},
    "Skin Corr. 1A": {"h_code": "H314", "cl": 5.0, "ghs": "GHS05"},
    "Skin Corr. 1B": {"h_code": "H314", "cl": 5.0, "ghs": "GHS05"},
    "Skin Corr. 1C": {"h_code": "H314", "cl": 5.0, "ghs": "GHS05"},
    "Skin Irrit. 2": {"h_code": "H315", "cl": 10.0, "ghs": "GHS07"},
    "Eye Dam. 1": {"h_code": "H318", "cl": 3.0, "ghs": "GHS05"},
    "Eye Irrit. 2": {"h_code": "H319", "cl": 10.0, "ghs": "GHS07"},
    "Skin Sens. 1": {"h_code": "H317", "cl": 1.0, "ghs": "GHS07"},
    "Skin Sens. 1A": {"h_code": "H317", "cl": 0.1, "ghs": "GHS07"},
    "Skin Sens. 1B": {"h_code": "H317", "cl": 1.0, "ghs": "GHS07"},
    "Resp. Sens. 1": {"h_code": "H334", "cl": 1.0, "ghs": "GHS08"},
    "Resp. Sens. 1A": {"h_code": "H334", "cl": 0.1, "ghs": "GHS08"},
    "Resp. Sens. 1B": {"h_code": "H334", "cl": 1.0, "ghs": "GHS08"},
    "Muta. 1A": {"h_code": "H340", "cl": 0.1, "ghs": "GHS08"},
    "Muta. 1B": {"h_code": "H340", "cl": 0.1, "ghs": "GHS08"},
    "Muta. 2": {"h_code": "H341", "cl": 1.0, "ghs": "GHS08"},
    "Carc. 1A": {"h_code": "H350", "cl": 0.1, "ghs": "GHS08"},
    "Carc. 1B": {"h_code": "H350", "cl": 0.1, "ghs": "GHS08"},
    "Carc. 2": {"h_code": "H351", "cl": 1.0, "ghs": "GHS08"},
    "Repr. 1A": {"h_code": "H360", "cl": 0.3, "ghs": "GHS08"},
    "Repr. 1B": {"h_code": "H360", "cl": 0.3, "ghs": "GHS08"},
    "Repr. 2": {"h_code": "H361", "cl": 3.0, "ghs": "GHS08"},
    "STOT SE 1": {"h_code": "H370", "cl": 10.0, "ghs": "GHS08"},
    "STOT SE 2": {"h_code": "H371", "cl": 10.0, "ghs": "GHS08"},
    "STOT SE 3": {"h_code": "H335", "cl": 20.0, "ghs": "GHS07"},
    "STOT RE 1": {"h_code": "H372", "cl": 10.0, "ghs": "GHS08"},
    "STOT RE 2": {"h_code": "H373", "cl": 10.0, "ghs": "GHS08"},
    "Aquatic Acute 1": {"h_code": "H400", "cl": 25.0, "ghs": "GHS09"},
    "Aquatic Chronic 1": {"h_code": "H410", "cl": 25.0, "ghs": "GHS09"},
    "Aquatic Chronic 2": {"h_code": "H411", "cl": 25.0, "ghs": "GHS09"},
    "Aquatic Chronic 3": {"h_code": "H412", "cl": 25.0, "ghs": "GHS09"},
    "Aquatic Chronic 4": {"h_code": "H413", "cl": 25.0, "ghs": "GHS09"},
    "Asp. Tox. 1": {"h_code": "H304", "cl": 10.0, "ghs": "GHS08"},
    # Akutní toxicita - dermální
    "Acute Tox. 1 (Dermal)": {"h_code": "H310", "cl": 3.0, "ghs": "GHS06"},
    "Acute Tox. 2 (Dermal)": {"h_code": "H310", "cl": 3.0, "ghs": "GHS06"},
    "Acute Tox. 3 (Dermal)": {"h_code": "H311", "cl": 10.0, "ghs": "GHS06"},
    "Acute Tox. 4 (Dermal)": {"h_code": "H312", "cl": 25.0, "ghs": "GHS07"},
    # Akutní toxicita - orální
    "Acute Tox. 1 (Oral)": {"h_code": "H300", "cl": 3.0, "ghs": "GHS06"},
    "Acute Tox. 2 (Oral)": {"h_code": "H300", "cl": 3.0, "ghs": "GHS06"},
    "Acute Tox. 3 (Oral)": {"h_code": "H301", "cl": 10.0, "ghs": "GHS06"},
    "Acute Tox. 4 (Oral)": {"h_code": "H302", "cl": 25.0, "ghs": "GHS07"},
    # Akutní toxicita - inhalační
    "Acute Tox. 1 (Inhalation)": {"h_code": "H330", "cl": 3.0, "ghs": "GHS06"},
    "Acute Tox. 2 (Inhalation)": {"h_code": "H330", "cl": 3.0, "ghs": "GHS06"},
    "Acute Tox. 3 (Inhalation)": {"h_code": "H331", "cl": 10.0, "ghs": "GHS06"},
    "Acute Tox. 4 (Inhalation)": {"h_code": "H332", "cl": 25.0, "ghs": "GHS07"},
}

HEALTH_H_PHRASES = {
    "H300": "Smrtelný při požití (AT Kat. 1/2)",
    "H301": "Toxický při požití (AT Kat. 3)",
    "H302": "Zdraví škodlivý při požití (AT Kat. 4)",
    "H310": "Smrtelný při styku s kůží (AT Kat. 1/2)",
    "H311": "Toxický při styku s kůží (AT Kat. 3)",
    "H312": "Zdraví škodlivý při styku s kůží (AT Kat. 4)",
    "H330": "Smrtelný při vdechování (AT Kat. 1/2)",
    "H331": "Toxický při vdechování (AT Kat. 3)",
    "H332": "Zdraví škodlivý při vdechování (AT Kat. 4)",
    "H314": "Způsobuje těžké poleptání kůže a poškození očí (Skin Corr. 1A/B/C)",
    "H315": "Dráždí kůži (Skin Irrit. 2)",
    "H318": "Způsobuje vážné poškození očí (Eye Dam. 1)",
    "H319": "Způsobuje vážné podráždění očí (Eye Irrit. 2)",
    "H317": "Může vyvolat alergickou kožní reakci (Skin Sens. 1)",
    "H334": "Může vyvolat příznaky alergie nebo astmatu nebo dýchací potíže (Resp. Sens. 1)",
    "H340": "Může vyvolat genetické poškození (Muta. 1A/1B)",
    "H350": "Může vyvolat rakovinu (Carc. 1A/1B)",
    "H360": "Může poškodit reprodukční schopnost nebo plod (Repr. 1A/1B)",
    "H370": "Způsobuje poškození orgánů (STOT SE 1)",
    "H372": "Způsobuje poškození orgánů při prodloužené expozici (STOT RE 1)",
    "H341": "Podezření na genetické poškození (Muta. 2)",
    "H351": "Podezření na vyvolání rakoviny (Carc. 2)",
    "H361": "Podezření na poškození reprodukční schopnosti nebo plodu (Repr. 2)",
    "H371": "Může způsobit poškození orgánů (STOT SE 2)",
    "H373": "Může způsobit poškození orgánů při prodloužené expozici (STOT RE 2)",
    "H335": "Může způsobit podráždění dýchacích cest (STOT SE 3)",
    "H336": "Může způsobit ospalost nebo závratě (STOT SE 3)",
    "H304": "Při požití a vniknutí do dýchacích cest může způsobit smrt (Asp. Tox. 1)",
    "H362": "Může poškodit kojence prostřednictvím mateřského mléka (Lact.)",
}

ENV_H_PHRASES = {
    "H400": "Vysoce toxický pro vodní organismy (Aquatic Acute 1)",
    "H410": "Vysoce toxický pro vodní organismy s dlouhodobými účinky (Aquatic Chronic 1)",
    "H411": "Toxický pro vodní organismy s dlouhodobými účinky (Aquatic Chronic 2)",
    "H412": "Škodlivý pro vodní organismy s dlouhodobými účinky (Aquatic Chronic 3)",
    "H413": "Může vyvolat dlouhodobé škodlivé účinky na vodní organismy (Aquatic Chronic 4)",
    "H420": "Poškozuje veřejné zdraví a životní prostředí tím, že ničí ozon ve vyšších vrstvách atmosféry (Ozone 1)",
}

EUH_PHRASES = {
    "EUH066": "Opakovaná expozice může způsobit vysušení nebo popraskání kůže.",
    "EUH208": "Obsahuje (název senzibilizující látky). Může vyvolat alergickou reakci.",
    "EUH210": "Na vyžádání je k dispozici bezpečnostní list.",
    "EUH430": "Může způsobit endokrinní rozvracení u lidí (ED HH 1).",
    "EUH431": "Podezření na vyvolání endokrinního rozvracení u lidí (ED HH 2).",
    "EUH440": "Může způsobit endokrinní rozvracení v životním prostředí (ED ENV 1).",
    "EUH441": "Podezření na vyvolání endokrinního rozvracení v životním prostředí (ED ENV 2).",
    "EUH450": "Může vyvolat dlouhodobé znečištění vodních zdrojů (PBT / vPvB).",
    "EUH451": "Může vyvolat velmi dlouhodobé znečištění vodních zdrojů (PMT / vPvM).",
}

SCL_HAZARD_TO_H_CODE = {
    "Skin Corr. 1": "H314",
    "Skin Corr. 1A": "H314",
    "Skin Corr. 1B": "H314",
    "Skin Corr. 1C": "H314",
    "Skin Irrit. 2": "H315",
    "Eye Dam. 1": "H318",
    "Eye Irrit. 2": "H319",
    "Skin Sens. 1": "H317",
    "Skin Sens. 1A": "H317",
    "Skin Sens. 1B": "H317",
    "Resp. Sens. 1": "H334",
    "Resp. Sens. 1A": "H334",
    "Resp. Sens. 1B": "H334",
    "Carc. 1A": "H350",
    "Carc. 1B": "H350",
    "Carc. 2": "H351",
    "Muta. 1A": "H340",
    "Muta. 1B": "H340",
    "Muta. 2": "H341",
    "Repr. 1A": "H360",
    "Repr. 1B": "H360",
    "Repr. 2": "H361",
    "STOT SE 1": "H370",
    "STOT SE 2": "H371",
    "STOT SE 3": "H335",
    "STOT SE 3 (Narcotic)": "H336",
    "STOT RE 1": "H372",
    "STOT RE 2": "H373",
    "Aquatic Acute 1": "H400",
    "Aquatic Chronic 1": "H410",
    "Aquatic Chronic 2": "H411",
    "Aquatic Chronic 3": "H412",
    "Aquatic Chronic 4": "H413",
    "Acute Tox. 1": "H300",
    "Acute Tox. 2": "H300",
    "Acute Tox. 3": "H301",
    "Acute Tox. 4": "H302",
    # Dermální akutní toxicita
    "Acute Tox. 1 (Dermal)": "H310",
    "Acute Tox. 2 (Dermal)": "H310",
    "Acute Tox. 3 (Dermal)": "H311",
    "Acute Tox. 4 (Dermal)": "H312",
    # Orální akutní toxicita
    "Acute Tox. 1 (Oral)": "H300",
    "Acute Tox. 2 (Oral)": "H300",
    "Acute Tox. 3 (Oral)": "H301",
    "Acute Tox. 4 (Oral)": "H302",
    # Inhalační akutní toxicita
    "Acute Tox. 1 (Inhalation)": "H330",
    "Acute Tox. 2 (Inhalation)": "H330",
    "Acute Tox. 3 (Inhalation)": "H331",
    "Acute Tox. 4 (Inhalation)": "H332",
}

SCL_HAZARD_TO_GHS_CODE = {
    "Skin Corr. 1A": "GHS05",
    "Skin Corr. 1B": "GHS05",
    "Skin Corr. 1C": "GHS05",
    "Skin Irrit. 2": "GHS07",
    "Eye Dam. 1": "GHS05",
    "Eye Irrit. 2": "GHS07",
    "Skin Sens. 1": "GHS07",
    "Skin Sens. 1A": "GHS07",
    "Skin Sens. 1B": "GHS07",
    "Resp. Sens. 1": "GHS08",
    "Resp. Sens. 1A": "GHS08",
    "Resp. Sens. 1B": "GHS08",
    "Carc. 1A": "GHS08",
    "Carc. 1B": "GHS08",
    "Carc. 2": "GHS08",
    "Muta. 1A": "GHS08",
    "Muta. 1B": "GHS08",
    "Muta. 2": "GHS08",
    "Repr. 1A": "GHS08",
    "Repr. 1B": "GHS08",
    "Repr. 2": "GHS08",
    "STOT SE 1": "GHS08",
    "STOT SE 2": "GHS08",
    "STOT SE 3": "GHS07",
    "STOT SE 3 (Narcotic)": "GHS07",
    "STOT RE 1": "GHS08",
    "STOT RE 2": "GHS08",
    "Aquatic Acute 1": "GHS09",
    "Aquatic Chronic 1": "GHS09",
    "Aquatic Chronic 2": "GHS09",
    "Aquatic Chronic 3": "GHS09",
    "Acute Tox. 1": "GHS06",
    "Acute Tox. 2": "GHS06",
    "Acute Tox. 3": "GHS06",
    "Acute Tox. 4": "GHS07",
    # Dermální akutní toxicita
    "Acute Tox. 1 (Dermal)": "GHS06",
    "Acute Tox. 2 (Dermal)": "GHS06",
    "Acute Tox. 3 (Dermal)": "GHS06",
    "Acute Tox. 4 (Dermal)": "GHS07",
    # Orální akutní toxicita
    "Acute Tox. 1 (Oral)": "GHS06",
    "Acute Tox. 2 (Oral)": "GHS06",
    "Acute Tox. 3 (Oral)": "GHS06",
    "Acute Tox. 4 (Oral)": "GHS07",
    # Inhalační akutní toxicita
    "Acute Tox. 1 (Inhalation)": "GHS06",
    "Acute Tox. 2 (Inhalation)": "GHS06",
    "Acute Tox. 3 (Inhalation)": "GHS06",
    "Acute Tox. 4 (Inhalation)": "GHS07",
}

SCL_HAZARD_CATEGORIES = sorted(list(set(SCL_HAZARD_TO_H_CODE.keys())))

H_PHRASES_DISPLAY = {
    "H300": ("Acute Tox. 1/2, H300", "Smrtelný při požití."),
    "H301": ("Acute Tox. 3, H301", "Toxický při požití."),
    "H302": ("Acute Tox. 4, H302", "Zdraví škodlivý při požití."),
    "H310": ("Acute Tox. 1/2, H310", "Smrtelný při styku s kůží."),
    "H311": ("Acute Tox. 3, H311", "Toxický při styku s kůží."),
    "H312": ("Acute Tox. 4, H312", "Zdraví škodlivý při styku s kůží."),
    "H330": ("Acute Tox. 1/2, H330", "Smrtelný při vdechování."),
    "H331": ("Acute Tox. 3, H331", "Toxický při vdechování."),
    "H332": ("Acute Tox. 4, H332", "Zdraví škodlivý při vdechování."),
    "H304": (
        "Asp. Tox. 1, H304",
        "Při požití a vniknutí do dýchacích cest může způsobit smrt.",
    ),
    "H314": ("Skin Corr. 1, H314", "Způsobuje těžké poleptání kůže a poškození očí."),
    "H315": ("Skin Irrit. 2, H315", "Dráždí kůži."),
    "H318": ("Eye Dam. 1, H318", "Způsobuje vážné poškození očí."),
    "H319": ("Eye Irrit. 2, H319", "Způsobuje vážné podráždění očí."),
    "H317": ("Skin Sens. 1, H317", "Může vyvolat alergickou kožní reakci."),
    "H334": (
        "Resp. Sens. 1, H334",
        "Může vyvolat příznaky alergie nebo astmatu nebo dýchací potíže při vdechování.",
    ),
    "H340": ("Muta. 1A/B, H340", "Může vyvolat genetické poškození."),
    "H341": ("Muta. 2, H341", "Podezření na genetické poškození."),
    "H350": ("Carc. 1A/B, H350", "Může vyvolat rakovinu."),
    "H351": ("Carc. 2, H351", "Podezření na vyvolání rakoviny."),
    "H360": (
        "Repr. 1A/B, H360",
        "Může poškodit reprodukční schopnost nebo plod v těle matky.",
    ),
    "H361": (
        "Repr. 2, H361",
        "Podezření na poškození reprodukční schopnosti nebo plodu v těle matky.",
    ),
    "H370": ("STOT SE 1, H370", "Způsobuje poškození orgánů."),
    "H371": ("STOT SE 2, H371", "Může způsobit poškození orgánů."),
    "H335": ("STOT SE 3, H335", "Může způsobit podráždění dýchacích cest."),
    "H336": ("STOT SE 3, H336", "Může způsobit ospalost nebo závratě."),
    "H372": (
        "STOT RE 1, H372",
        "Způsobuje poškození orgánů při prodloužené nebo opakované expozici.",
    ),
    "H373": (
        "STOT RE 2, H373",
        "Může způsobit poškození orgánů při prodloužené nebo opakované expozici.",
    ),
    "H400": ("Aquatic Acute 1, H400", "Vysoce toxický pro vodní organismy."),
    "H410": (
        "Aquatic Chronic 1, H410",
        "Vysoce toxický pro vodní organismy, s dlouhodobými účinky.",
    ),
    "H411": (
        "Aquatic Chronic 2, H411",
        "Toxický pro vodní organismy, s dlouhodobými účinky.",
    ),
    "H412": (
        "Aquatic Chronic 3, H412",
        "Škodlivý pro vodní organismy, s dlouhodobými účinky.",
    ),
    "H413": (
        "Aquatic Chronic 4, H413",
        "Může vyvolat dlouhodobé škodlivé účinky pro vodní organismy.",
    ),
    "H362": ("Lact., H362", "Může poškodit kojence prostřednictvím mateřského mléka."),
    "H420": ("Ozone 1, H420", "Poškozuje ozonovou vrstvu."),
    "EUH066": ("EUH066", "Opakovaná expozice může způsobit vysušení nebo popraskání kůže."),
    "EUH208": ("EUH208", "Obsahuje senzibilizující látku. Může vyvolat alergickou reakci."),
    "EUH210": ("EUH210", "Na vyžádání je k dispozici bezpečnostní list."),
    "EUH430": ("ED HH 1, EUH430", "Může způsobit endokrinní rozvracení u lidí."),
    "EUH431": ("ED HH 2, EUH431", "Podezření na vyvolání endokrinního rozvracení u lidí."),
    "EUH440": ("ED ENV 1, EUH440", "Může způsobit endokrinní rozvracení v životním prostředí."),
    "EUH441": ("ED ENV 2, EUH441", "Podezření na vyvolání endokrinního rozvracení v životním prostředí."),
    "EUH450": ("PBT / vPvB, EUH450", "Může vyvolat dlouhodobé znečištění vodních zdrojů."),
    "EUH451": ("PMT / vPvM, EUH451", "Může vyvolat velmi dlouhodobé znečištění vodních zdrojů."),
}
