"""Add_physical_state_fields

Revision ID: 15a0a59235ea
Revises: 3b46686f1b68
Create Date: 2026-01-16 22:25:37.590648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a0a59235ea'
down_revision = '3b46686f1b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physical_state', sa.Enum('LIQUID', 'SOLID', 'GAS', 'AEROSOL', name='physicalstate'), nullable=False, server_default='LIQUID'))
        batch_op.add_column(sa.Column('flash_point', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('boiling_point', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_column('boiling_point')
        batch_op.drop_column('flash_point')
        batch_op.drop_column('physical_state')

    # ### end Alembic commands ###
