"""Add CLP 2026 columns

Revision ID: 247a14bb42f0
Revises: 733496d9f1bd
Create Date: 2026-01-07 20:07:35.037324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247a14bb42f0'
down_revision = '733496d9f1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lact', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ed_hh_cat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ed_env_cat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_pbt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_vpvb', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_pmt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_vpvm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_ozone', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.drop_column('has_ozone')
        batch_op.drop_column('is_vpvm')
        batch_op.drop_column('is_pmt')
        batch_op.drop_column('is_vpvb')
        batch_op.drop_column('is_pbt')
        batch_op.drop_column('ed_env_cat')
        batch_op.drop_column('ed_hh_cat')
        batch_op.drop_column('is_lact')

    # ### end Alembic commands ###
