"""Add ph and unknown_env to mixture

Revision ID: 3b46686f1b68
Revises: 163235988ff3
Create Date: 2026-01-14 21:52:13.744562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b46686f1b68'
down_revision = '163235988ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unknown_env_toxicity_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_column('unknown_env_toxicity_percent')
        batch_op.drop_column('ph')

    # ### end Alembic commands ###
