"""Refactor ecotoxicity: variant A - specific fields for standard CLP tests

Revision ID: 7154063ef3f8
Revises: 82600b03d50a
Create Date: 2026-01-20 18:12:16.912290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7154063ef3f8'
down_revision = '82600b03d50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lc50_fish_96h', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ec50_daphnia_48h', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ec50_algae_72h', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noec_chronic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ld50_oral_mammal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ld50_dermal_mammal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lc50_inhalation_rat_4h', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.drop_column('lc50_inhalation_rat_4h')
        batch_op.drop_column('ld50_dermal_mammal')
        batch_op.drop_column('ld50_oral_mammal')
        batch_op.drop_column('noec_chronic')
        batch_op.drop_column('ec50_algae_72h')
        batch_op.drop_column('ec50_daphnia_48h')
        batch_op.drop_column('lc50_fish_96h')

    # ### end Alembic commands ###
