"""Initial complete migration

Revision ID: 733496d9f1bd
Revises: 
Create Date: 2026-01-06 22:26:09.542804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733496d9f1bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('final_health_hazards', sa.Text(), nullable=True),
    sa.Column('final_environmental_hazards', sa.Text(), nullable=True),
    sa.Column('final_ghs_codes', sa.String(length=100), nullable=True),
    sa.Column('final_atemix_oral', sa.Float(), nullable=True),
    sa.Column('final_atemix_dermal', sa.Float(), nullable=True),
    sa.Column('final_atemix_inhalation', sa.Float(), nullable=True),
    sa.Column('final_signal_word', sa.String(length=50), nullable=True),
    sa.Column('classification_log', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mixture_created_date'), ['created_date'], unique=False)

    op.create_table('substance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cas_number', sa.String(length=20), nullable=True),
    sa.Column('ghs_codes', sa.String(length=100), nullable=True),
    sa.Column('health_h_phrases', sa.Text(), nullable=True),
    sa.Column('env_h_phrases', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ate_oral', sa.Float(), nullable=True),
    sa.Column('ate_dermal', sa.Float(), nullable=True),
    sa.Column('ate_inhalation_vapours', sa.Float(), nullable=True),
    sa.Column('ate_inhalation_dusts_mists', sa.Float(), nullable=True),
    sa.Column('ate_inhalation_gases', sa.Float(), nullable=True),
    sa.Column('m_factor_acute', sa.Integer(), nullable=True),
    sa.Column('m_factor_chronic', sa.Integer(), nullable=True),
    sa.Column('scl_limits', sa.Text(), nullable=True),
    sa.CheckConstraint('ate_dermal >= 0', name='check_ate_dermal_positive'),
    sa.CheckConstraint('ate_inhalation_dusts_mists >= 0', name='check_ate_dusts_positive'),
    sa.CheckConstraint('ate_inhalation_gases >= 0', name='check_ate_gases_positive'),
    sa.CheckConstraint('ate_inhalation_vapours >= 0', name='check_ate_vapours_positive'),
    sa.CheckConstraint('ate_oral >= 0', name='check_ate_oral_positive'),
    sa.CheckConstraint('m_factor_acute >= 1', name='check_m_acute_positive'),
    sa.CheckConstraint('m_factor_chronic >= 1', name='check_m_chronic_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substance_cas_number'), ['cas_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_substance_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mixture_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mixture_id', sa.Integer(), nullable=False),
    sa.Column('substance_id', sa.Integer(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.CheckConstraint('concentration > 0 AND concentration <= 100', name='check_concentration_range'),
    sa.ForeignKeyConstraint(['mixture_id'], ['mixture.id'], ),
    sa.ForeignKeyConstraint(['substance_id'], ['substance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mixture_id', 'substance_id', name='_mixture_substance_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mixture_component')
    op.drop_table('user')
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_substance_name'))
        batch_op.drop_index(batch_op.f('ix_substance_cas_number'))

    op.drop_table('substance')
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mixture_created_date'))

    op.drop_table('mixture')
    # ### end Alembic commands ###
