"""Add molecular_weight to Substance

Revision ID: 82600b03d50a
Revises: f99787264a54
Create Date: 2026-01-17 19:31:40.536209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82600b03d50a'
down_revision = 'f99787264a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('molecular_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.drop_column('molecular_weight')

    # ### end Alembic commands ###
