"""Add_final_physical_hazards_column

Revision ID: 886e39dc30a1
Revises: 15a0a59235ea
Create Date: 2026-01-16 22:28:59.503705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886e39dc30a1'
down_revision = '15a0a59235ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_physical_hazards', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_column('final_physical_hazards')

    # ### end Alembic commands ###
