"""Add component_type and component_mixture_id to MixtureComponent

Revision ID: a1b2c3d4e5f6
Revises: 82600b03d50a
Create Date: 2026-01-22 21:22:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'cf4956b65d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture_component', schema=None) as batch_op:
        # Přidat nový sloupec component_type s výchozí hodnotou 'substance'
        batch_op.add_column(sa.Column('component_type', sa.Enum('SUBSTANCE', 'MIXTURE', name='componenttype'), nullable=False, server_default='SUBSTANCE'))
        
        # Přidat sloupec pro vazbu na směs
        batch_op.add_column(sa.Column('component_mixture_id', sa.Integer(), nullable=True))
        
        # Upravit substance_id na nullable
        batch_op.alter_column('substance_id', existing_type=sa.INTEGER(), nullable=True)
        
        # Přidat foreign key pro component_mixture_id
        batch_op.create_foreign_key('fk_component_mixture', 'mixture', ['component_mixture_id'], ['id'])
        
        # Odstranit starý unique constraint
        batch_op.drop_constraint('_mixture_substance_uc', type_='unique')
        
        # Přidat nový check constraint pro konzistenci typu
        batch_op.create_check_constraint(
            'check_component_type_consistency',
            "(component_type = 'SUBSTANCE' AND substance_id IS NOT NULL AND component_mixture_id IS NULL) OR "
            "(component_type = 'MIXTURE' AND component_mixture_id IS NOT NULL AND substance_id IS NULL)"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture_component', schema=None) as batch_op:
        # Odstranit check constraint
        batch_op.drop_constraint('check_component_type_consistency', type_='check')
        
        # Přidat zpět unique constraint
        batch_op.create_unique_constraint('_mixture_substance_uc', ['mixture_id', 'substance_id'])
        
        # Odstranit foreign key
        batch_op.drop_constraint('fk_component_mixture', type_='foreignkey')
        
        # Upravit substance_id zpět na not nullable
        batch_op.alter_column('substance_id', existing_type=sa.INTEGER(), nullable=False)
        
        # Odstranit nové sloupce
        batch_op.drop_column('component_mixture_id')
        batch_op.drop_column('component_type')

    # ### end Alembic commands ###
