"""Add physical_h_phrases

Revision ID: cf4956b65d5f
Revises: 5c0e530439fa
Create Date: 2026-01-22 20:32:47.011763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4956b65d5f'
down_revision = '5c0e530439fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physical_h_phrases', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.drop_column('physical_h_phrases')

    # ### end Alembic commands ###
