"""Add P-phrases

Revision ID: d1063025fdbf
Revises: efe2b3df324a
Create Date: 2026-01-17 16:38:57.071197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1063025fdbf'
down_revision = 'efe2b3df324a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_precautionary_statements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_column('final_precautionary_statements')

    # ### end Alembic commands ###
