"""Add user_type to Mixture

Revision ID: e15b05bfdf8c
Revises: d1063025fdbf
Create Date: 2026-01-17 17:20:22.693944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15b05bfdf8c'
down_revision = 'd1063025fdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Enum('CONSUMER', 'PROFESSIONAL', 'INDUSTRIAL', name='usertype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
