"""Add is_svhc to Substance

Revision ID: eefe9e6d3152
Revises: e15b05bfdf8c
Create Date: 2026-01-17 17:52:03.372129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefe9e6d3152'
down_revision = 'e15b05bfdf8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_svhc', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.drop_column('is_svhc')

    # ### end Alembic commands ###
