"""Add_can_generate_mist

Revision ID: efe2b3df324a
Revises: 886e39dc30a1
Create Date: 2026-01-16 22:57:06.352634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe2b3df324a'
down_revision = '886e39dc30a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_generate_mist', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixture', schema=None) as batch_op:
        batch_op.drop_column('can_generate_mist')

    # ### end Alembic commands ###
