"""Add REACH Annex columns to Substance

Revision ID: f99787264a54
Revises: eefe9e6d3152
Create Date: 2026-01-17 18:13:53.335147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99787264a54'
down_revision = 'eefe9e6d3152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reach_annex_xiv', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_reach_annex_xvii', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance', schema=None) as batch_op:
        batch_op.drop_column('is_reach_annex_xvii')
        batch_op.drop_column('is_reach_annex_xiv')

    # ### end Alembic commands ###
